### PR TITLE
feat: added get all keys feature

### PR DESCRIPTION
**Pull request by danielbatica**
I added a new API to the store: getAllKeys. It returns the exiting keys for the partition.
Added impl, unit tests, e2e, docs.

## Motivation and Context

We use aio-state-lib for Adobe's AEM Screens Cloud. We need to get all stored keys.
Jira story: http://jira.corp.adobe.com/browse/SCRNS-1287

## How Has This Been Tested?

Added e2e test that passes. Used an AIO runtime namespace

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by meryllblanchet** [comment]
Thanks for this complete PR, @danielbatica ! We'll review next week, stay tuned.

**Comment by bdelacretaz** [comment]
I'm not working on this code but I have alarms go on when I see a `getAllSomething` method that doesn't set limits on the number of items returned ;-)

What if you have a hundred million keys?

I think the method should either implement some form of paging for the results, or at least set a limit on the size of the array returned.

**Comment by danielbatica** [comment]
> I'm not working on this code but I have alarms go on when I see a `getAllSomething` method that doesn't set limits on the number of items returned ;-)
> 
> What if you have a hundred million keys?
> 
> I think the method should either implement some form of paging for the results, or at least set a limit on the size of the array returned.
 Makes sense, It would be easy if the underlying cosmosdb would provide that since this is just a wrapper.

**Comment by meryllblanchet** [comment]
Hi @danielbatica , we've been discussing your PR and we'll keep it on hold for now: we have indeed a very similar PR from @sandeep-paliwal which had been deferred, for the following reasons:

- We want to be cautious about what and how we expose in terms of security, runtime performance and costs. For the two last items, this kind of operation run against a large set of States can be very impactful for all users, as we do share a single storage and RUs for all underlying namespaces.

- We consider an abstracted search with pagination as an alternative, with restrictions on what can be searched and how

- We want the abstraction to be provider agnostic to preserve the Bring Your Own Storage paradigm possible (e.g. and let developers bring a DynamoDB instance or other if needed)

Nevertheless this feature is frequently asked by our users. As an immediate next step, @sandeep-paliwal will go through a usage analysis of our OOTB storage so that we could assess the possible impact as early mentioned.
We'll keep you in the loop and follow-up with you to enhance your PR according to our feedback.

cc @sarahxxu for her additional input

**Comment by moritzraho** [comment]
closing as this is implemented in the new State majors (> v4). Legacy State users can refer to this PR to manually implement listing.

**Pull request closed without merging**
