### PR TITLE
feat!: DeleteAll match pattern and v5 adjustments

### PR DESCRIPTION
**Pull request by moritzraho**
## Description

MAJOR: This will go in v5

Add support for a match pattern for deleting a selected set of keys.

Breaking changes:
- deleteAll safeguard, must set the `match` option
- https://github.com/adobe/aio-lib-state/pull/175

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by MichaelGoberling — APPROVED** [review]

**Review by shazron — APPROVED** [review]
just double checking - if the dev just calls `deleteAll(()` it will fail right? (based on the regex) and they have to add `*` to match if they want to delete everything.

**Comment by shazron** [comment]
nvm - I see that the test is there where `deleteAll` should delete everything. Giving me nightmares if somehow I had a typo in there or wrong/null object. Perhaps as a "confirmation" step, where if you really want to deleteAll it should really be `deleteAll({ match: '*' })` WDYT?

**Comment by moritzraho** [comment]
> nvm - I see that the test is there where `deleteAll` should delete everything. Giving me nightmares if somehow I had a typo in there or wrong/null object. Perhaps as a "confirmation" step, where if you really want to deleteAll it should really be `deleteAll({ match: '*' })` WDYT?

yes felt this too, now the issue is that we already exposed `deleteAll()`... and because this is already used as part of the  deleteService we would need to make it a breaking change. Which could be acceptable at that point, wdyt?

**Review by MichaelGoberling — APPROVED** [review]
lgtm!

**Review by shazron — APPROVED** [review]

**Pull request merged**
