### PR TITLE
Added support to list stored keys.

### PR DESCRIPTION
**Pull request by sandeep-paliwal**
Added sdk method `list` to list stored keys.
Listing supports pagination using continuationTokens.

## How Has This Been Tested?
unit tests and manual test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Review by purplecabbage — COMMENTED** [review]
Looks like a good start, I added some nit/suggestions.
I am most concerned about the overhead of having this api.  As @moritzraho pointed out in other discussions, this is a heavy operation and we might not want to allow it at all, or find a way to optimize/monitor it so it is not abused.

**Comment by purplecabbage** [comment]
#60

**Review by moritzraho — COMMENTED** [review]
@sandeep-paliwal @purplecabbage happy to see that we are getting into this long awaited feature! 
This is a good start but we have delayed this feature for a while now (for good reasons) and I think it is important that we take the time to get this abstraction right. Goals are: minimize consumed Cosmos RUs and be user friendly.

Here are a few points I would like to discuss with you:

## 1. Query instead of list

I think what users really want here is a search/query instead of list and this would be less wasteful in terms of consumed RUs. Consider this typical pattern that would emerge if we expose just list:
```
list = await state.list() => lists all keys, is expensive
list.keys.filter(k => k.includes('keylabel_')
```
The user needs to first fetch all the keys to then filter them. This is neither optimized for RUs (cost) nor performance (usability).

A faster and cheaper approach would be to do something like:
```
list = await state.search({ keyPrefix: 'keylabel_' })
```
Here the search prefix would be translated by the sdk to a cosmosDB query and cosmosDB would return less keys meaning less RUs and faster roundtrip.

Using a `keyPrefix` is just an example, happy to hear better suggestions for query/search

## 2. Pagination

Should we handle pagination with a default value of max returned elements that can be overwritten via an option (but should be in a certain range) ?

```
await state.search({ limit: 50 })
```

## 3. Return values if needed
In some cases users might want to get the values, which would require them to send `n` additional `get` requests after the `search` operation. An easy optimization would be an option to return values too.

```
await state.search({ includeValue: true })
```

## 4. return `AsyncIterator`
Instead of returning all keys (and values) we could investigate into returning an `AsyncIterator` 


cc @Himavanth @meryllblanchet @rajarju @sarahxxu @shazron

**Comment by sandeep-paliwal** [comment]
Moving PR to draft as we may need more discussion around this.

**Comment by purplecabbage** [comment]
Closing as `on-hold`

**Comment by davidjgonzalez** [comment]
This would be incredibly useful, assuming you can implement it in a performant manner. What was the reason for closing this?

**Comment by shazron** [comment]
See https://github.com/adobe/aio-lib-state/pull/65#issuecomment-826866531

**Pull request closed without merging**
